// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clientmocks

import (
	"context"
	"sync"
)

// ThunderClientMock is a mock implementation of thundersvc.ThunderClient.
//
//	func TestSomethingThatUsesThunderClient(t *testing.T) {
//
//		// make and configure a mocked thundersvc.ThunderClient
//		mockedThunderClient := &ThunderClientMock{
//			CreateAgentIdentityFunc: func(ctx context.Context, ouID string, name string, owner string) (string, string, string, bool, error) {
//				panic("mock out the CreateAgentIdentity method")
//			},
//			DeleteAgentIdentityFunc: func(ctx context.Context, thunderAgentID string) (bool, error) {
//				panic("mock out the DeleteAgentIdentity method")
//			},
//			DeleteAppFunc: func(ctx context.Context, appName string) (bool, error) {
//				panic("mock out the DeleteApp method")
//			},
//			DeletePublisherAppFunc: func(ctx context.Context, orgName string) (bool, error) {
//				panic("mock out the DeletePublisherApp method")
//			},
//			EnsureAppFunc: func(ctx context.Context, appName string, orgUUID string) (string, string, bool, error) {
//				panic("mock out the EnsureApp method")
//			},
//			EnsurePublisherAppFunc: func(ctx context.Context, orgName string, orgUUID string) (string, string, bool, error) {
//				panic("mock out the EnsurePublisherApp method")
//			},
//			GetDefaultOUIDFunc: func(ctx context.Context) (string, error) {
//				panic("mock out the GetDefaultOUID method")
//			},
//			RegenerateAgentSecretFunc: func(ctx context.Context, thunderAgentID string) (string, error) {
//				panic("mock out the RegenerateAgentSecret method")
//			},
//			RegenerateAppClientSecretFunc: func(ctx context.Context, appName string) (string, error) {
//				panic("mock out the RegenerateAppClientSecret method")
//			},
//			RegenerateClientSecretFunc: func(ctx context.Context, orgName string) (string, error) {
//				panic("mock out the RegenerateClientSecret method")
//			},
//		}
//
//		// use mockedThunderClient in code that requires thundersvc.ThunderClient
//		// and then make assertions.
//
//	}
type ThunderClientMock struct {
	// CreateAgentIdentityFunc mocks the CreateAgentIdentity method.
	CreateAgentIdentityFunc func(ctx context.Context, ouID string, name string, owner string) (string, string, string, bool, error)

	// DeleteAgentIdentityFunc mocks the DeleteAgentIdentity method.
	DeleteAgentIdentityFunc func(ctx context.Context, thunderAgentID string) (bool, error)

	// DeleteAppFunc mocks the DeleteApp method.
	DeleteAppFunc func(ctx context.Context, appName string) (bool, error)

	// DeletePublisherAppFunc mocks the DeletePublisherApp method.
	DeletePublisherAppFunc func(ctx context.Context, orgName string) (bool, error)

	// EnsureAppFunc mocks the EnsureApp method.
	EnsureAppFunc func(ctx context.Context, appName string, orgUUID string) (string, string, bool, error)

	// EnsurePublisherAppFunc mocks the EnsurePublisherApp method.
	EnsurePublisherAppFunc func(ctx context.Context, orgName string, orgUUID string) (string, string, bool, error)

	// GetDefaultOUIDFunc mocks the GetDefaultOUID method.
	GetDefaultOUIDFunc func(ctx context.Context) (string, error)

	// RegenerateAgentSecretFunc mocks the RegenerateAgentSecret method.
	RegenerateAgentSecretFunc func(ctx context.Context, thunderAgentID string) (string, error)

	// RegenerateAppClientSecretFunc mocks the RegenerateAppClientSecret method.
	RegenerateAppClientSecretFunc func(ctx context.Context, appName string) (string, error)

	// RegenerateClientSecretFunc mocks the RegenerateClientSecret method.
	RegenerateClientSecretFunc func(ctx context.Context, orgName string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateAgentIdentity holds details about calls to the CreateAgentIdentity method.
		CreateAgentIdentity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// Name is the name argument value.
			Name string
			// Owner is the owner argument value.
			Owner string
		}
		// DeleteAgentIdentity holds details about calls to the DeleteAgentIdentity method.
		DeleteAgentIdentity []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ThunderAgentID is the thunderAgentID argument value.
			ThunderAgentID string
		}
		// DeleteApp holds details about calls to the DeleteApp method.
		DeleteApp []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AppName is the appName argument value.
			AppName string
		}
		// DeletePublisherApp holds details about calls to the DeletePublisherApp method.
		DeletePublisherApp []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
		// EnsureApp holds details about calls to the EnsureApp method.
		EnsureApp []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AppName is the appName argument value.
			AppName string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// EnsurePublisherApp holds details about calls to the EnsurePublisherApp method.
		EnsurePublisherApp []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
			// OrgUUID is the orgUUID argument value.
			OrgUUID string
		}
		// GetDefaultOUID holds details about calls to the GetDefaultOUID method.
		GetDefaultOUID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// RegenerateAgentSecret holds details about calls to the RegenerateAgentSecret method.
		RegenerateAgentSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ThunderAgentID is the thunderAgentID argument value.
			ThunderAgentID string
		}
		// RegenerateAppClientSecret holds details about calls to the RegenerateAppClientSecret method.
		RegenerateAppClientSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AppName is the appName argument value.
			AppName string
		}
		// RegenerateClientSecret holds details about calls to the RegenerateClientSecret method.
		RegenerateClientSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OrgName is the orgName argument value.
			OrgName string
		}
	}
	lockCreateAgentIdentity       sync.RWMutex
	lockDeleteAgentIdentity       sync.RWMutex
	lockDeleteApp                 sync.RWMutex
	lockDeletePublisherApp        sync.RWMutex
	lockEnsureApp                 sync.RWMutex
	lockEnsurePublisherApp        sync.RWMutex
	lockGetDefaultOUID            sync.RWMutex
	lockRegenerateAgentSecret     sync.RWMutex
	lockRegenerateAppClientSecret sync.RWMutex
	lockRegenerateClientSecret    sync.RWMutex
}

// CreateAgentIdentity calls CreateAgentIdentityFunc.
func (mock *ThunderClientMock) CreateAgentIdentity(ctx context.Context, ouID string, name string, owner string) (string, string, string, bool, error) {
	if mock.CreateAgentIdentityFunc == nil {
		panic("ThunderClientMock.CreateAgentIdentityFunc: method is nil but ThunderClient.CreateAgentIdentity was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OuID  string
		Name  string
		Owner string
	}{
		Ctx:   ctx,
		OuID:  ouID,
		Name:  name,
		Owner: owner,
	}
	mock.lockCreateAgentIdentity.Lock()
	mock.calls.CreateAgentIdentity = append(mock.calls.CreateAgentIdentity, callInfo)
	mock.lockCreateAgentIdentity.Unlock()
	return mock.CreateAgentIdentityFunc(ctx, ouID, name, owner)
}

// CreateAgentIdentityCalls gets all the calls that were made to CreateAgentIdentity.
// Check the length with:
//
//	len(mockedThunderClient.CreateAgentIdentityCalls())
func (mock *ThunderClientMock) CreateAgentIdentityCalls() []struct {
	Ctx   context.Context
	OuID  string
	Name  string
	Owner string
} {
	var calls []struct {
		Ctx   context.Context
		OuID  string
		Name  string
		Owner string
	}
	mock.lockCreateAgentIdentity.RLock()
	calls = mock.calls.CreateAgentIdentity
	mock.lockCreateAgentIdentity.RUnlock()
	return calls
}

// DeleteAgentIdentity calls DeleteAgentIdentityFunc.
func (mock *ThunderClientMock) DeleteAgentIdentity(ctx context.Context, thunderAgentID string) (bool, error) {
	if mock.DeleteAgentIdentityFunc == nil {
		panic("ThunderClientMock.DeleteAgentIdentityFunc: method is nil but ThunderClient.DeleteAgentIdentity was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ThunderAgentID string
	}{
		Ctx:            ctx,
		ThunderAgentID: thunderAgentID,
	}
	mock.lockDeleteAgentIdentity.Lock()
	mock.calls.DeleteAgentIdentity = append(mock.calls.DeleteAgentIdentity, callInfo)
	mock.lockDeleteAgentIdentity.Unlock()
	return mock.DeleteAgentIdentityFunc(ctx, thunderAgentID)
}

// DeleteAgentIdentityCalls gets all the calls that were made to DeleteAgentIdentity.
// Check the length with:
//
//	len(mockedThunderClient.DeleteAgentIdentityCalls())
func (mock *ThunderClientMock) DeleteAgentIdentityCalls() []struct {
	Ctx            context.Context
	ThunderAgentID string
} {
	var calls []struct {
		Ctx            context.Context
		ThunderAgentID string
	}
	mock.lockDeleteAgentIdentity.RLock()
	calls = mock.calls.DeleteAgentIdentity
	mock.lockDeleteAgentIdentity.RUnlock()
	return calls
}

// DeleteApp calls DeleteAppFunc.
func (mock *ThunderClientMock) DeleteApp(ctx context.Context, appName string) (bool, error) {
	if mock.DeleteAppFunc == nil {
		panic("ThunderClientMock.DeleteAppFunc: method is nil but ThunderClient.DeleteApp was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		AppName string
	}{
		Ctx:     ctx,
		AppName: appName,
	}
	mock.lockDeleteApp.Lock()
	mock.calls.DeleteApp = append(mock.calls.DeleteApp, callInfo)
	mock.lockDeleteApp.Unlock()
	return mock.DeleteAppFunc(ctx, appName)
}

// DeleteAppCalls gets all the calls that were made to DeleteApp.
// Check the length with:
//
//	len(mockedThunderClient.DeleteAppCalls())
func (mock *ThunderClientMock) DeleteAppCalls() []struct {
	Ctx     context.Context
	AppName string
} {
	var calls []struct {
		Ctx     context.Context
		AppName string
	}
	mock.lockDeleteApp.RLock()
	calls = mock.calls.DeleteApp
	mock.lockDeleteApp.RUnlock()
	return calls
}

// DeletePublisherApp calls DeletePublisherAppFunc.
func (mock *ThunderClientMock) DeletePublisherApp(ctx context.Context, orgName string) (bool, error) {
	if mock.DeletePublisherAppFunc == nil {
		panic("ThunderClientMock.DeletePublisherAppFunc: method is nil but ThunderClient.DeletePublisherApp was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockDeletePublisherApp.Lock()
	mock.calls.DeletePublisherApp = append(mock.calls.DeletePublisherApp, callInfo)
	mock.lockDeletePublisherApp.Unlock()
	return mock.DeletePublisherAppFunc(ctx, orgName)
}

// DeletePublisherAppCalls gets all the calls that were made to DeletePublisherApp.
// Check the length with:
//
//	len(mockedThunderClient.DeletePublisherAppCalls())
func (mock *ThunderClientMock) DeletePublisherAppCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockDeletePublisherApp.RLock()
	calls = mock.calls.DeletePublisherApp
	mock.lockDeletePublisherApp.RUnlock()
	return calls
}

// EnsureApp calls EnsureAppFunc.
func (mock *ThunderClientMock) EnsureApp(ctx context.Context, appName string, orgUUID string) (string, string, bool, error) {
	if mock.EnsureAppFunc == nil {
		panic("ThunderClientMock.EnsureAppFunc: method is nil but ThunderClient.EnsureApp was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		AppName string
		OrgUUID string
	}{
		Ctx:     ctx,
		AppName: appName,
		OrgUUID: orgUUID,
	}
	mock.lockEnsureApp.Lock()
	mock.calls.EnsureApp = append(mock.calls.EnsureApp, callInfo)
	mock.lockEnsureApp.Unlock()
	return mock.EnsureAppFunc(ctx, appName, orgUUID)
}

// EnsureAppCalls gets all the calls that were made to EnsureApp.
// Check the length with:
//
//	len(mockedThunderClient.EnsureAppCalls())
func (mock *ThunderClientMock) EnsureAppCalls() []struct {
	Ctx     context.Context
	AppName string
	OrgUUID string
} {
	var calls []struct {
		Ctx     context.Context
		AppName string
		OrgUUID string
	}
	mock.lockEnsureApp.RLock()
	calls = mock.calls.EnsureApp
	mock.lockEnsureApp.RUnlock()
	return calls
}

// EnsurePublisherApp calls EnsurePublisherAppFunc.
func (mock *ThunderClientMock) EnsurePublisherApp(ctx context.Context, orgName string, orgUUID string) (string, string, bool, error) {
	if mock.EnsurePublisherAppFunc == nil {
		panic("ThunderClientMock.EnsurePublisherAppFunc: method is nil but ThunderClient.EnsurePublisherApp was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
		OrgUUID string
	}{
		Ctx:     ctx,
		OrgName: orgName,
		OrgUUID: orgUUID,
	}
	mock.lockEnsurePublisherApp.Lock()
	mock.calls.EnsurePublisherApp = append(mock.calls.EnsurePublisherApp, callInfo)
	mock.lockEnsurePublisherApp.Unlock()
	return mock.EnsurePublisherAppFunc(ctx, orgName, orgUUID)
}

// EnsurePublisherAppCalls gets all the calls that were made to EnsurePublisherApp.
// Check the length with:
//
//	len(mockedThunderClient.EnsurePublisherAppCalls())
func (mock *ThunderClientMock) EnsurePublisherAppCalls() []struct {
	Ctx     context.Context
	OrgName string
	OrgUUID string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
		OrgUUID string
	}
	mock.lockEnsurePublisherApp.RLock()
	calls = mock.calls.EnsurePublisherApp
	mock.lockEnsurePublisherApp.RUnlock()
	return calls
}

// GetDefaultOUID calls GetDefaultOUIDFunc.
func (mock *ThunderClientMock) GetDefaultOUID(ctx context.Context) (string, error) {
	if mock.GetDefaultOUIDFunc == nil {
		panic("ThunderClientMock.GetDefaultOUIDFunc: method is nil but ThunderClient.GetDefaultOUID was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetDefaultOUID.Lock()
	mock.calls.GetDefaultOUID = append(mock.calls.GetDefaultOUID, callInfo)
	mock.lockGetDefaultOUID.Unlock()
	return mock.GetDefaultOUIDFunc(ctx)
}

// GetDefaultOUIDCalls gets all the calls that were made to GetDefaultOUID.
// Check the length with:
//
//	len(mockedThunderClient.GetDefaultOUIDCalls())
func (mock *ThunderClientMock) GetDefaultOUIDCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetDefaultOUID.RLock()
	calls = mock.calls.GetDefaultOUID
	mock.lockGetDefaultOUID.RUnlock()
	return calls
}

// RegenerateAgentSecret calls RegenerateAgentSecretFunc.
func (mock *ThunderClientMock) RegenerateAgentSecret(ctx context.Context, thunderAgentID string) (string, error) {
	if mock.RegenerateAgentSecretFunc == nil {
		panic("ThunderClientMock.RegenerateAgentSecretFunc: method is nil but ThunderClient.RegenerateAgentSecret was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ThunderAgentID string
	}{
		Ctx:            ctx,
		ThunderAgentID: thunderAgentID,
	}
	mock.lockRegenerateAgentSecret.Lock()
	mock.calls.RegenerateAgentSecret = append(mock.calls.RegenerateAgentSecret, callInfo)
	mock.lockRegenerateAgentSecret.Unlock()
	return mock.RegenerateAgentSecretFunc(ctx, thunderAgentID)
}

// RegenerateAgentSecretCalls gets all the calls that were made to RegenerateAgentSecret.
// Check the length with:
//
//	len(mockedThunderClient.RegenerateAgentSecretCalls())
func (mock *ThunderClientMock) RegenerateAgentSecretCalls() []struct {
	Ctx            context.Context
	ThunderAgentID string
} {
	var calls []struct {
		Ctx            context.Context
		ThunderAgentID string
	}
	mock.lockRegenerateAgentSecret.RLock()
	calls = mock.calls.RegenerateAgentSecret
	mock.lockRegenerateAgentSecret.RUnlock()
	return calls
}

// RegenerateAppClientSecret calls RegenerateAppClientSecretFunc.
func (mock *ThunderClientMock) RegenerateAppClientSecret(ctx context.Context, appName string) (string, error) {
	if mock.RegenerateAppClientSecretFunc == nil {
		panic("ThunderClientMock.RegenerateAppClientSecretFunc: method is nil but ThunderClient.RegenerateAppClientSecret was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		AppName string
	}{
		Ctx:     ctx,
		AppName: appName,
	}
	mock.lockRegenerateAppClientSecret.Lock()
	mock.calls.RegenerateAppClientSecret = append(mock.calls.RegenerateAppClientSecret, callInfo)
	mock.lockRegenerateAppClientSecret.Unlock()
	return mock.RegenerateAppClientSecretFunc(ctx, appName)
}

// RegenerateAppClientSecretCalls gets all the calls that were made to RegenerateAppClientSecret.
// Check the length with:
//
//	len(mockedThunderClient.RegenerateAppClientSecretCalls())
func (mock *ThunderClientMock) RegenerateAppClientSecretCalls() []struct {
	Ctx     context.Context
	AppName string
} {
	var calls []struct {
		Ctx     context.Context
		AppName string
	}
	mock.lockRegenerateAppClientSecret.RLock()
	calls = mock.calls.RegenerateAppClientSecret
	mock.lockRegenerateAppClientSecret.RUnlock()
	return calls
}

// RegenerateClientSecret calls RegenerateClientSecretFunc.
func (mock *ThunderClientMock) RegenerateClientSecret(ctx context.Context, orgName string) (string, error) {
	if mock.RegenerateClientSecretFunc == nil {
		panic("ThunderClientMock.RegenerateClientSecretFunc: method is nil but ThunderClient.RegenerateClientSecret was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OrgName string
	}{
		Ctx:     ctx,
		OrgName: orgName,
	}
	mock.lockRegenerateClientSecret.Lock()
	mock.calls.RegenerateClientSecret = append(mock.calls.RegenerateClientSecret, callInfo)
	mock.lockRegenerateClientSecret.Unlock()
	return mock.RegenerateClientSecretFunc(ctx, orgName)
}

// RegenerateClientSecretCalls gets all the calls that were made to RegenerateClientSecret.
// Check the length with:
//
//	len(mockedThunderClient.RegenerateClientSecretCalls())
func (mock *ThunderClientMock) RegenerateClientSecretCalls() []struct {
	Ctx     context.Context
	OrgName string
} {
	var calls []struct {
		Ctx     context.Context
		OrgName string
	}
	mock.lockRegenerateClientSecret.RLock()
	calls = mock.calls.RegenerateClientSecret
	mock.lockRegenerateClientSecret.RUnlock()
	return calls
}
