/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the TracingTokenRegenerateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TracingTokenRegenerateRequest{}

// TracingTokenRegenerateRequest struct for TracingTokenRegenerateRequest
type TracingTokenRegenerateRequest struct {
	// Environment in which to rotate the agent's tracing token
	EnvironmentName string `json:"environmentName"`
	// Optional token expiry duration in Go duration format (e.g., \"2160h\" for 90 days). If not provided, the default expiry from configuration is used.
	ExpiresIn *string `json:"expiresIn,omitempty"`
}

// NewTracingTokenRegenerateRequest instantiates a new TracingTokenRegenerateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTracingTokenRegenerateRequest(environmentName string) *TracingTokenRegenerateRequest {
	this := TracingTokenRegenerateRequest{}
	this.EnvironmentName = environmentName
	return &this
}

// NewTracingTokenRegenerateRequestWithDefaults instantiates a new TracingTokenRegenerateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTracingTokenRegenerateRequestWithDefaults() *TracingTokenRegenerateRequest {
	this := TracingTokenRegenerateRequest{}
	return &this
}

// GetEnvironmentName returns the EnvironmentName field value
func (o *TracingTokenRegenerateRequest) GetEnvironmentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value
// and a boolean to check if the value has been set.
func (o *TracingTokenRegenerateRequest) GetEnvironmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentName, true
}

// SetEnvironmentName sets field value
func (o *TracingTokenRegenerateRequest) SetEnvironmentName(v string) {
	o.EnvironmentName = v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *TracingTokenRegenerateRequest) GetExpiresIn() string {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret string
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TracingTokenRegenerateRequest) GetExpiresInOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *TracingTokenRegenerateRequest) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given string and assigns it to the ExpiresIn field.
func (o *TracingTokenRegenerateRequest) SetExpiresIn(v string) {
	o.ExpiresIn = &v
}

func (o TracingTokenRegenerateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TracingTokenRegenerateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentName"] = o.EnvironmentName
	if !IsNil(o.ExpiresIn) {
		toSerialize["expiresIn"] = o.ExpiresIn
	}
	return toSerialize, nil
}

type NullableTracingTokenRegenerateRequest struct {
	value *TracingTokenRegenerateRequest
	isSet bool
}

func (v NullableTracingTokenRegenerateRequest) Get() *TracingTokenRegenerateRequest {
	return v.value
}

func (v *NullableTracingTokenRegenerateRequest) Set(val *TracingTokenRegenerateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTracingTokenRegenerateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTracingTokenRegenerateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTracingTokenRegenerateRequest(val *TracingTokenRegenerateRequest) *NullableTracingTokenRegenerateRequest {
	return &NullableTracingTokenRegenerateRequest{value: val, isSet: true}
}

func (v NullableTracingTokenRegenerateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTracingTokenRegenerateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
