/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ThunderUrlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThunderUrlRequest{}

// ThunderUrlRequest An unguessable handle to register for an environment's env-Thunder URL, replacing the predictable \"<org>-<env>\" pattern. Optional — omit it (or send an empty string) to have the server generate one.
type ThunderUrlRequest struct {
	// DNS-label-safe handle (lowercase alphanumeric with hyphens, no leading/trailing hyphen) that replaces \"<org>-<env>\" in \"<handle>.<baseDomain>\". Must be globally unique across all orgs/environments, and at least 10 characters (matching what the server itself generates — anything shorter is trivially guessable). Omit to auto-generate a 10-character handle.
	Handle *string `json:"handle,omitempty"`
}

// NewThunderUrlRequest instantiates a new ThunderUrlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThunderUrlRequest() *ThunderUrlRequest {
	this := ThunderUrlRequest{}
	return &this
}

// NewThunderUrlRequestWithDefaults instantiates a new ThunderUrlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThunderUrlRequestWithDefaults() *ThunderUrlRequest {
	this := ThunderUrlRequest{}
	return &this
}

// GetHandle returns the Handle field value if set, zero value otherwise.
func (o *ThunderUrlRequest) GetHandle() string {
	if o == nil || IsNil(o.Handle) {
		var ret string
		return ret
	}
	return *o.Handle
}

// GetHandleOk returns a tuple with the Handle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThunderUrlRequest) GetHandleOk() (*string, bool) {
	if o == nil || IsNil(o.Handle) {
		return nil, false
	}
	return o.Handle, true
}

// HasHandle returns a boolean if a field has been set.
func (o *ThunderUrlRequest) HasHandle() bool {
	if o != nil && !IsNil(o.Handle) {
		return true
	}

	return false
}

// SetHandle gets a reference to the given string and assigns it to the Handle field.
func (o *ThunderUrlRequest) SetHandle(v string) {
	o.Handle = &v
}

func (o ThunderUrlRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThunderUrlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Handle) {
		toSerialize["handle"] = o.Handle
	}
	return toSerialize, nil
}

type NullableThunderUrlRequest struct {
	value *ThunderUrlRequest
	isSet bool
}

func (v NullableThunderUrlRequest) Get() *ThunderUrlRequest {
	return v.value
}

func (v *NullableThunderUrlRequest) Set(val *ThunderUrlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableThunderUrlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableThunderUrlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThunderUrlRequest(val *ThunderUrlRequest) *NullableThunderUrlRequest {
	return &NullableThunderUrlRequest{value: val, isSet: true}
}

func (v NullableThunderUrlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThunderUrlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
