/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentSummary{}

// AgentSummary struct for AgentSummary
type AgentSummary struct {
	Name               string `json:"name"`
	DisplayName        string `json:"displayName"`
	ProjectName        string `json:"projectName"`
	ProjectDisplayName string `json:"projectDisplayName"`
}

// NewAgentSummary instantiates a new AgentSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentSummary(name string, displayName string, projectName string, projectDisplayName string) *AgentSummary {
	this := AgentSummary{}
	this.Name = name
	this.DisplayName = displayName
	this.ProjectName = projectName
	this.ProjectDisplayName = projectDisplayName
	return &this
}

// NewAgentSummaryWithDefaults instantiates a new AgentSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentSummaryWithDefaults() *AgentSummary {
	this := AgentSummary{}
	return &this
}

// GetName returns the Name field value
func (o *AgentSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentSummary) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *AgentSummary) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *AgentSummary) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *AgentSummary) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetProjectName returns the ProjectName field value
func (o *AgentSummary) GetProjectName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value
// and a boolean to check if the value has been set.
func (o *AgentSummary) GetProjectNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectName, true
}

// SetProjectName sets field value
func (o *AgentSummary) SetProjectName(v string) {
	o.ProjectName = v
}

// GetProjectDisplayName returns the ProjectDisplayName field value
func (o *AgentSummary) GetProjectDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectDisplayName
}

// GetProjectDisplayNameOk returns a tuple with the ProjectDisplayName field value
// and a boolean to check if the value has been set.
func (o *AgentSummary) GetProjectDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectDisplayName, true
}

// SetProjectDisplayName sets field value
func (o *AgentSummary) SetProjectDisplayName(v string) {
	o.ProjectDisplayName = v
}

func (o AgentSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	toSerialize["projectName"] = o.ProjectName
	toSerialize["projectDisplayName"] = o.ProjectDisplayName
	return toSerialize, nil
}

type NullableAgentSummary struct {
	value *AgentSummary
	isSet bool
}

func (v NullableAgentSummary) Get() *AgentSummary {
	return v.value
}

func (v *NullableAgentSummary) Set(val *AgentSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentSummary(val *AgentSummary) *NullableAgentSummary {
	return &NullableAgentSummary{value: val, isSet: true}
}

func (v NullableAgentSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
