/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the TracingTokenRegenerateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TracingTokenRegenerateResponse{}

// TracingTokenRegenerateResponse struct for TracingTokenRegenerateResponse
type TracingTokenRegenerateResponse struct {
	// Environment in which the tracing API key was rotated
	EnvironmentName string `json:"environmentName"`
	// Unix timestamp when the new API key expires
	ExpiresAt int64 `json:"expiresAt"`
	// Unix timestamp when the API key was rotated
	RotatedAt int64 `json:"rotatedAt"`
}

// NewTracingTokenRegenerateResponse instantiates a new TracingTokenRegenerateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTracingTokenRegenerateResponse(environmentName string, expiresAt int64, rotatedAt int64) *TracingTokenRegenerateResponse {
	this := TracingTokenRegenerateResponse{}
	this.EnvironmentName = environmentName
	this.ExpiresAt = expiresAt
	this.RotatedAt = rotatedAt
	return &this
}

// NewTracingTokenRegenerateResponseWithDefaults instantiates a new TracingTokenRegenerateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTracingTokenRegenerateResponseWithDefaults() *TracingTokenRegenerateResponse {
	this := TracingTokenRegenerateResponse{}
	return &this
}

// GetEnvironmentName returns the EnvironmentName field value
func (o *TracingTokenRegenerateResponse) GetEnvironmentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvironmentName
}

// GetEnvironmentNameOk returns a tuple with the EnvironmentName field value
// and a boolean to check if the value has been set.
func (o *TracingTokenRegenerateResponse) GetEnvironmentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvironmentName, true
}

// SetEnvironmentName sets field value
func (o *TracingTokenRegenerateResponse) SetEnvironmentName(v string) {
	o.EnvironmentName = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *TracingTokenRegenerateResponse) GetExpiresAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *TracingTokenRegenerateResponse) GetExpiresAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *TracingTokenRegenerateResponse) SetExpiresAt(v int64) {
	o.ExpiresAt = v
}

// GetRotatedAt returns the RotatedAt field value
func (o *TracingTokenRegenerateResponse) GetRotatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RotatedAt
}

// GetRotatedAtOk returns a tuple with the RotatedAt field value
// and a boolean to check if the value has been set.
func (o *TracingTokenRegenerateResponse) GetRotatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotatedAt, true
}

// SetRotatedAt sets field value
func (o *TracingTokenRegenerateResponse) SetRotatedAt(v int64) {
	o.RotatedAt = v
}

func (o TracingTokenRegenerateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TracingTokenRegenerateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["environmentName"] = o.EnvironmentName
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["rotatedAt"] = o.RotatedAt
	return toSerialize, nil
}

type NullableTracingTokenRegenerateResponse struct {
	value *TracingTokenRegenerateResponse
	isSet bool
}

func (v NullableTracingTokenRegenerateResponse) Get() *TracingTokenRegenerateResponse {
	return v.value
}

func (v *NullableTracingTokenRegenerateResponse) Set(val *TracingTokenRegenerateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTracingTokenRegenerateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTracingTokenRegenerateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTracingTokenRegenerateResponse(val *TracingTokenRegenerateResponse) *NullableTracingTokenRegenerateResponse {
	return &NullableTracingTokenRegenerateResponse{value: val, isSet: true}
}

func (v NullableTracingTokenRegenerateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTracingTokenRegenerateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
