/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"fmt"
)

// GatewayTypeInput Gateway placement role accepted on input. `REGULAR` and `AI` are deprecated aliases kept for gateway charts pinned to an older version (REGULAR -> BOTH, AI -> EGRESS); prefer INGRESS/EGRESS/BOTH. Responses and the canonical `GatewayType` schema never emit REGULAR/AI.
type GatewayTypeInput string

// List of GatewayTypeInput
const (
	GATEWAYTYPEINPUT_INGRESS GatewayTypeInput = "INGRESS"
	GATEWAYTYPEINPUT_EGRESS  GatewayTypeInput = "EGRESS"
	GATEWAYTYPEINPUT_BOTH    GatewayTypeInput = "BOTH"
	GATEWAYTYPEINPUT_REGULAR GatewayTypeInput = "REGULAR"
	GATEWAYTYPEINPUT_AI      GatewayTypeInput = "AI"
)

// All allowed values of GatewayTypeInput enum
var AllowedGatewayTypeInputEnumValues = []GatewayTypeInput{
	"INGRESS",
	"EGRESS",
	"BOTH",
	"REGULAR",
	"AI",
}

func (v *GatewayTypeInput) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GatewayTypeInput(value)
	for _, existing := range AllowedGatewayTypeInputEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GatewayTypeInput", value)
}

// NewGatewayTypeInputFromValue returns a pointer to a valid GatewayTypeInput
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGatewayTypeInputFromValue(v string) (*GatewayTypeInput, error) {
	ev := GatewayTypeInput(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GatewayTypeInput: valid values are %v", v, AllowedGatewayTypeInputEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GatewayTypeInput) IsValid() bool {
	for _, existing := range AllowedGatewayTypeInputEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GatewayTypeInput value
func (v GatewayTypeInput) Ptr() *GatewayTypeInput {
	return &v
}

type NullableGatewayTypeInput struct {
	value *GatewayTypeInput
	isSet bool
}

func (v NullableGatewayTypeInput) Get() *GatewayTypeInput {
	return v.value
}

func (v *NullableGatewayTypeInput) Set(val *GatewayTypeInput) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayTypeInput) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayTypeInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayTypeInput(val *GatewayTypeInput) *NullableGatewayTypeInput {
	return &NullableGatewayTypeInput{value: val, isSet: true}
}

func (v NullableGatewayTypeInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayTypeInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
