/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentSummaryListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentSummaryListResponse{}

// AgentSummaryListResponse struct for AgentSummaryListResponse
type AgentSummaryListResponse struct {
	Agents []AgentSummary `json:"agents"`
}

// NewAgentSummaryListResponse instantiates a new AgentSummaryListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentSummaryListResponse(agents []AgentSummary) *AgentSummaryListResponse {
	this := AgentSummaryListResponse{}
	this.Agents = agents
	return &this
}

// NewAgentSummaryListResponseWithDefaults instantiates a new AgentSummaryListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentSummaryListResponseWithDefaults() *AgentSummaryListResponse {
	this := AgentSummaryListResponse{}
	return &this
}

// GetAgents returns the Agents field value
func (o *AgentSummaryListResponse) GetAgents() []AgentSummary {
	if o == nil {
		var ret []AgentSummary
		return ret
	}

	return o.Agents
}

// GetAgentsOk returns a tuple with the Agents field value
// and a boolean to check if the value has been set.
func (o *AgentSummaryListResponse) GetAgentsOk() ([]AgentSummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Agents, true
}

// SetAgents sets field value
func (o *AgentSummaryListResponse) SetAgents(v []AgentSummary) {
	o.Agents = v
}

func (o AgentSummaryListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentSummaryListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agents"] = o.Agents
	return toSerialize, nil
}

type NullableAgentSummaryListResponse struct {
	value *AgentSummaryListResponse
	isSet bool
}

func (v NullableAgentSummaryListResponse) Get() *AgentSummaryListResponse {
	return v.value
}

func (v *NullableAgentSummaryListResponse) Set(val *AgentSummaryListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentSummaryListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentSummaryListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentSummaryListResponse(val *AgentSummaryListResponse) *NullableAgentSummaryListResponse {
	return &NullableAgentSummaryListResponse{value: val, isSet: true}
}

func (v NullableAgentSummaryListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentSummaryListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
