/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the ThunderUrlAvailabilityResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThunderUrlAvailabilityResponse{}

// ThunderUrlAvailabilityResponse Whether a candidate env-Thunder URL handle passes format validation and is not already registered to any environment. Advisory only — see checkThunderUrlAvailability.
type ThunderUrlAvailabilityResponse struct {
	// True if the handle is well-formed and not currently taken.
	Available bool `json:"available"`
}

// NewThunderUrlAvailabilityResponse instantiates a new ThunderUrlAvailabilityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThunderUrlAvailabilityResponse(available bool) *ThunderUrlAvailabilityResponse {
	this := ThunderUrlAvailabilityResponse{}
	this.Available = available
	return &this
}

// NewThunderUrlAvailabilityResponseWithDefaults instantiates a new ThunderUrlAvailabilityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThunderUrlAvailabilityResponseWithDefaults() *ThunderUrlAvailabilityResponse {
	this := ThunderUrlAvailabilityResponse{}
	return &this
}

// GetAvailable returns the Available field value
func (o *ThunderUrlAvailabilityResponse) GetAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *ThunderUrlAvailabilityResponse) GetAvailableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Available, true
}

// SetAvailable sets field value
func (o *ThunderUrlAvailabilityResponse) SetAvailable(v bool) {
	o.Available = v
}

func (o ThunderUrlAvailabilityResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThunderUrlAvailabilityResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["available"] = o.Available
	return toSerialize, nil
}

type NullableThunderUrlAvailabilityResponse struct {
	value *ThunderUrlAvailabilityResponse
	isSet bool
}

func (v NullableThunderUrlAvailabilityResponse) Get() *ThunderUrlAvailabilityResponse {
	return v.value
}

func (v *NullableThunderUrlAvailabilityResponse) Set(val *ThunderUrlAvailabilityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableThunderUrlAvailabilityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableThunderUrlAvailabilityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThunderUrlAvailabilityResponse(val *ThunderUrlAvailabilityResponse) *NullableThunderUrlAvailabilityResponse {
	return &NullableThunderUrlAvailabilityResponse{value: val, isSet: true}
}

func (v NullableThunderUrlAvailabilityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThunderUrlAvailabilityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
