/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
)

// checks if the AgentCreatedBy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentCreatedBy{}

// AgentCreatedBy The user who created this agent. Resolved from an audit-only requester id captured at creation time, so it is best-effort and omitted entirely when unknown (e.g. agents created before this was tracked, or where the creating user could not be resolved).
type AgentCreatedBy struct {
	// User ID of the creator
	Id string `json:"id"`
	// Display name/username of the creator, when resolvable. Omitted if the user has since been deleted.
	Display *string `json:"display,omitempty"`
}

// NewAgentCreatedBy instantiates a new AgentCreatedBy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentCreatedBy(id string) *AgentCreatedBy {
	this := AgentCreatedBy{}
	this.Id = id
	return &this
}

// NewAgentCreatedByWithDefaults instantiates a new AgentCreatedBy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentCreatedByWithDefaults() *AgentCreatedBy {
	this := AgentCreatedBy{}
	return &this
}

// GetId returns the Id field value
func (o *AgentCreatedBy) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AgentCreatedBy) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AgentCreatedBy) SetId(v string) {
	o.Id = v
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *AgentCreatedBy) GetDisplay() string {
	if o == nil || IsNil(o.Display) {
		var ret string
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentCreatedBy) GetDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.Display) {
		return nil, false
	}
	return o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *AgentCreatedBy) HasDisplay() bool {
	if o != nil && !IsNil(o.Display) {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given string and assigns it to the Display field.
func (o *AgentCreatedBy) SetDisplay(v string) {
	o.Display = &v
}

func (o AgentCreatedBy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentCreatedBy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Display) {
		toSerialize["display"] = o.Display
	}
	return toSerialize, nil
}

type NullableAgentCreatedBy struct {
	value *AgentCreatedBy
	isSet bool
}

func (v NullableAgentCreatedBy) Get() *AgentCreatedBy {
	return v.value
}

func (v *NullableAgentCreatedBy) Set(val *AgentCreatedBy) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentCreatedBy) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentCreatedBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentCreatedBy(val *AgentCreatedBy) *NullableAgentCreatedBy {
	return &NullableAgentCreatedBy{value: val, isSet: true}
}

func (v NullableAgentCreatedBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentCreatedBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
