// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// EnvThunderURLRepositoryMock is a mock implementation of repositories.EnvThunderURLRepository.
//
//	func TestSomethingThatUsesEnvThunderURLRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.EnvThunderURLRepository
//		mockedEnvThunderURLRepository := &EnvThunderURLRepositoryMock{
//			DeleteFunc: func(ctx context.Context, ouID string, envName string) error {
//				panic("mock out the Delete method")
//			},
//			ExistsByHandleFunc: func(ctx context.Context, handle string) (bool, error) {
//				panic("mock out the ExistsByHandle method")
//			},
//			GetFunc: func(ctx context.Context, ouID string, envName string) (*models.EnvThunderURL, error) {
//				panic("mock out the Get method")
//			},
//			InsertFunc: func(ctx context.Context, rec *models.EnvThunderURL) error {
//				panic("mock out the Insert method")
//			},
//		}
//
//		// use mockedEnvThunderURLRepository in code that requires repositories.EnvThunderURLRepository
//		// and then make assertions.
//
//	}
type EnvThunderURLRepositoryMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, ouID string, envName string) error

	// ExistsByHandleFunc mocks the ExistsByHandle method.
	ExistsByHandleFunc func(ctx context.Context, handle string) (bool, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, ouID string, envName string) (*models.EnvThunderURL, error)

	// InsertFunc mocks the Insert method.
	InsertFunc func(ctx context.Context, rec *models.EnvThunderURL) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// EnvName is the envName argument value.
			EnvName string
		}
		// ExistsByHandle holds details about calls to the ExistsByHandle method.
		ExistsByHandle []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Handle is the handle argument value.
			Handle string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// EnvName is the envName argument value.
			EnvName string
		}
		// Insert holds details about calls to the Insert method.
		Insert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rec is the rec argument value.
			Rec *models.EnvThunderURL
		}
	}
	lockDelete         sync.RWMutex
	lockExistsByHandle sync.RWMutex
	lockGet            sync.RWMutex
	lockInsert         sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *EnvThunderURLRepositoryMock) Delete(ctx context.Context, ouID string, envName string) error {
	if mock.DeleteFunc == nil {
		panic("EnvThunderURLRepositoryMock.DeleteFunc: method is nil but EnvThunderURLRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OuID    string
		EnvName string
	}{
		Ctx:     ctx,
		OuID:    ouID,
		EnvName: envName,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, ouID, envName)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedEnvThunderURLRepository.DeleteCalls())
func (mock *EnvThunderURLRepositoryMock) DeleteCalls() []struct {
	Ctx     context.Context
	OuID    string
	EnvName string
} {
	var calls []struct {
		Ctx     context.Context
		OuID    string
		EnvName string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ExistsByHandle calls ExistsByHandleFunc.
func (mock *EnvThunderURLRepositoryMock) ExistsByHandle(ctx context.Context, handle string) (bool, error) {
	if mock.ExistsByHandleFunc == nil {
		panic("EnvThunderURLRepositoryMock.ExistsByHandleFunc: method is nil but EnvThunderURLRepository.ExistsByHandle was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Handle string
	}{
		Ctx:    ctx,
		Handle: handle,
	}
	mock.lockExistsByHandle.Lock()
	mock.calls.ExistsByHandle = append(mock.calls.ExistsByHandle, callInfo)
	mock.lockExistsByHandle.Unlock()
	return mock.ExistsByHandleFunc(ctx, handle)
}

// ExistsByHandleCalls gets all the calls that were made to ExistsByHandle.
// Check the length with:
//
//	len(mockedEnvThunderURLRepository.ExistsByHandleCalls())
func (mock *EnvThunderURLRepositoryMock) ExistsByHandleCalls() []struct {
	Ctx    context.Context
	Handle string
} {
	var calls []struct {
		Ctx    context.Context
		Handle string
	}
	mock.lockExistsByHandle.RLock()
	calls = mock.calls.ExistsByHandle
	mock.lockExistsByHandle.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *EnvThunderURLRepositoryMock) Get(ctx context.Context, ouID string, envName string) (*models.EnvThunderURL, error) {
	if mock.GetFunc == nil {
		panic("EnvThunderURLRepositoryMock.GetFunc: method is nil but EnvThunderURLRepository.Get was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OuID    string
		EnvName string
	}{
		Ctx:     ctx,
		OuID:    ouID,
		EnvName: envName,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, ouID, envName)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedEnvThunderURLRepository.GetCalls())
func (mock *EnvThunderURLRepositoryMock) GetCalls() []struct {
	Ctx     context.Context
	OuID    string
	EnvName string
} {
	var calls []struct {
		Ctx     context.Context
		OuID    string
		EnvName string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Insert calls InsertFunc.
func (mock *EnvThunderURLRepositoryMock) Insert(ctx context.Context, rec *models.EnvThunderURL) error {
	if mock.InsertFunc == nil {
		panic("EnvThunderURLRepositoryMock.InsertFunc: method is nil but EnvThunderURLRepository.Insert was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Rec *models.EnvThunderURL
	}{
		Ctx: ctx,
		Rec: rec,
	}
	mock.lockInsert.Lock()
	mock.calls.Insert = append(mock.calls.Insert, callInfo)
	mock.lockInsert.Unlock()
	return mock.InsertFunc(ctx, rec)
}

// InsertCalls gets all the calls that were made to Insert.
// Check the length with:
//
//	len(mockedEnvThunderURLRepository.InsertCalls())
func (mock *EnvThunderURLRepositoryMock) InsertCalls() []struct {
	Ctx context.Context
	Rec *models.EnvThunderURL
} {
	var calls []struct {
		Ctx context.Context
		Rec *models.EnvThunderURL
	}
	mock.lockInsert.RLock()
	calls = mock.calls.Insert
	mock.lockInsert.RUnlock()
	return calls
}
