// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"sync"

	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// OrgSchedulerCredentialRepositoryMock is a mock implementation of repositories.OrgSchedulerCredentialRepository.
//
//	func TestSomethingThatUsesOrgSchedulerCredentialRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.OrgSchedulerCredentialRepository
//		mockedOrgSchedulerCredentialRepository := &OrgSchedulerCredentialRepositoryMock{
//			GetByOrgNameFunc: func(ouID string) (*models.OrgSchedulerCredential, error) {
//				panic("mock out the GetByOrgName method")
//			},
//			UpsertFunc: func(cred *models.OrgSchedulerCredential) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedOrgSchedulerCredentialRepository in code that requires repositories.OrgSchedulerCredentialRepository
//		// and then make assertions.
//
//	}
type OrgSchedulerCredentialRepositoryMock struct {
	// GetByOrgNameFunc mocks the GetByOrgName method.
	GetByOrgNameFunc func(ouID string) (*models.OrgSchedulerCredential, error)

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(cred *models.OrgSchedulerCredential) error

	// calls tracks calls to the methods.
	calls struct {
		// GetByOrgName holds details about calls to the GetByOrgName method.
		GetByOrgName []struct {
			// OuID is the ouID argument value.
			OuID string
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Cred is the cred argument value.
			Cred *models.OrgSchedulerCredential
		}
	}
	lockGetByOrgName sync.RWMutex
	lockUpsert       sync.RWMutex
}

// GetByOrgName calls GetByOrgNameFunc.
func (mock *OrgSchedulerCredentialRepositoryMock) GetByOrgName(ouID string) (*models.OrgSchedulerCredential, error) {
	if mock.GetByOrgNameFunc == nil {
		panic("OrgSchedulerCredentialRepositoryMock.GetByOrgNameFunc: method is nil but OrgSchedulerCredentialRepository.GetByOrgName was just called")
	}
	callInfo := struct {
		OuID string
	}{
		OuID: ouID,
	}
	mock.lockGetByOrgName.Lock()
	mock.calls.GetByOrgName = append(mock.calls.GetByOrgName, callInfo)
	mock.lockGetByOrgName.Unlock()
	return mock.GetByOrgNameFunc(ouID)
}

// GetByOrgNameCalls gets all the calls that were made to GetByOrgName.
// Check the length with:
//
//	len(mockedOrgSchedulerCredentialRepository.GetByOrgNameCalls())
func (mock *OrgSchedulerCredentialRepositoryMock) GetByOrgNameCalls() []struct {
	OuID string
} {
	var calls []struct {
		OuID string
	}
	mock.lockGetByOrgName.RLock()
	calls = mock.calls.GetByOrgName
	mock.lockGetByOrgName.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *OrgSchedulerCredentialRepositoryMock) Upsert(cred *models.OrgSchedulerCredential) error {
	if mock.UpsertFunc == nil {
		panic("OrgSchedulerCredentialRepositoryMock.UpsertFunc: method is nil but OrgSchedulerCredentialRepository.Upsert was just called")
	}
	callInfo := struct {
		Cred *models.OrgSchedulerCredential
	}{
		Cred: cred,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(cred)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedOrgSchedulerCredentialRepository.UpsertCalls())
func (mock *OrgSchedulerCredentialRepositoryMock) UpsertCalls() []struct {
	Cred *models.OrgSchedulerCredential
} {
	var calls []struct {
		Cred *models.OrgSchedulerCredential
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}
