{{- if not .Values.amObserver.observer.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: observer-idp-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  idpClientId: {{ required "amObserver.observer.idpClientId is required" .Values.amObserver.observer.idpClientId | quote }}
  idpClientSecret: {{ required "amObserver.observer.idpClientSecret or existingSecret is required" .Values.amObserver.observer.idpClientSecret | quote }}
{{- end }}
